title: Kaik Marques
#logo: /assets/img/heafshot_circle.png #onde a minha imagem pessoal está alocada no git hub
#description: text below image
show_downloads: true #mostra o download do código, false não mostra
them: jekyll-theme-minimal
